### ISSUE TITLE
Parse doubles like ".1"

### ISSUE THREAD

**Issue by tkvogt** [bos/attoparsec#100]
I write a SVG parser for diagrams: [diagrams-input](https://github.com/diagrams/diagrams-input) Some images have attributes like: opacity=".1" instead of "0.1". It would be nice if the double parser would accept this.

**Comment by bos** [comment]
What you want is a revived version of #44, which no longer applies cleanly.

**Comment by tkvogt** [comment]
I solved it like this

import           Data.Digits(digits)

myDouble = AT.choice [dotDouble, double]

dotDouble =
   do AT.skipSpace
      AT.char '.'
      frac <- AT.decimal
      let denominator = fromIntegral (10^(length $ digits 10 frac))
      return ((fromIntegral frac) / denominator)
