### ISSUE TITLE
Travis is not running for this Repo

### ISSUE THREAD

**Issue by zhujinxuan** [bos/attoparsec#147]
Hi, it seems the travis is not running for PRs.  I run the `travis lint .travis.yml`. I did not see any errors, so I am not sure why travis is not working...

```
Warnings for .travis.yml:
[x] in matrix.include.compiler section: illegal value ghc-8.2.2, defaulting to gcc
[x] in matrix.include section: unexpected key addons, dropping
[x] in matrix.include.compiler section: illegal value ghc-8.0.2, defaulting to gcc
[x] in matrix.include.compiler section: illegal value ghc-7.10.3, defaulting to gcc
[x] in matrix.include.compiler section: illegal value ghc-7.8.4, defaulting to gcc
[x] in matrix.include.compiler section: illegal value ghc-7.6.3, defaulting to gcc
[x] in matrix.include.compiler section: illegal value ghc-7.4.2, defaulting to gcc
[x] in matrix.include.compiler section: illegal value ghc-7.2.2, defaulting to gcc
[x] in matrix.include.compiler section: illegal value ghc-7.0.4, defaulting to gcc
```

If a new travis.yml is needed, I can submit a travis.yml based on stack like in https://github.com/ixmatus/orgmode-parse/pull/41.

Thank you,
Jinxuan Zhu

**Comment by bgamari** [comment]
The reason is that @bos has not enabled it. I have pinged him requesting we transfer ownership of the repository to me but he has not yet replied. Feel free to submit your PR to bgamari/attoparsec in the meantime.
