### ISSUE TITLE
Types in Data.Attoparsec.Char8 shouldn't be Word8, should they?

### ISSUE THREAD

**Issue by afcowie** [bos/attoparsec#27]
Data.Attoparsec.Char8 generally has predicates of the type `(Char -> Bool)`, for example `isSpace`, and functions like `takeTill` and `takeWhile` take such predicates, having type `(Char -> Bool) -> Parser ByteString`.

Shouldn't the `isEndOfLine` and `isHorizontalSpace` predicate functions similarly be specialized to `(Char -> Bool)`? Right now they are `(Word8 -> Bool)` which make them difficult to use with `takeTill`.

AfC

**Comment by bos** [comment]
It's more trouble to move them than to leave the situation as-is, alas.

**Comment by liyang** [comment]
@bos Can we leave this ticket open? We have our own local `Data.Attoparsec.Char8` that `PackageImports` the one from `attoparsec` and ‘fixes’ exactly this issue.

**Comment by bos** [comment]
Well, the point of keeping a bug open is to indicate either that it hasn't been read or that a fix might happen some day. In this case, I've read it and provisionally decided that it's valid but not to fix it, so why keep it open?

**Comment by dschrempf** [comment]
I also think that the current situation is confusing. As already stated: `isSpace` is working with `Char`, but `isHorizontalSpace` with `Word8`. It may be easier to leave the situation as is, but it is certainly more clear to have consistent types.
