### ISSUE TITLE
How to get (slightly) better errors?

### ISSUE THREAD

**Issue by singpolyma** [bos/attoparsec#49]
I know that if I want "really good" errors I should switch to parsec, but right now I have the issue where, say:

    parser = (char '=' >> option Nothing fmap (Just piece)) <?> "Path"
    piece = takeWhile1 (\x -> x /= '/' && x /= '*' && not (isSpace x))
    
    parseOnly (parser <* endOfLine <* endOfInput)

when fed with, say, just an "x" gives an error message of "satisfy".  Would be nice if I could at least say something like "Syntax error in Path".

**Comment by bos** [comment]
I've applied #79, which adds context to error messages.
