### ISSUE TITLE
Function request: findAll

### ISSUE THREAD

**Issue by varosi** [bos/attoparsec#82]
Is it possible to add a function that is finding all matches inside a string, like:

import Data.Either (rights)
import Data.Attoparsec.Text (Parser, parseOnly)
import Data.Text (pack)

findAll :: Parser a -> String -> [a]
findAll parser = rights . map (parseOnly parser . pack) . oneLess where
            oneLess []             = []
            oneLess (whole@(_:xs)) = whole : oneLess xs

**Comment by bos** [comment]
It's possible to write such a function, but it should be based on the `stringsearch` library for efficiency – and I don't think I'd take a patch that applied it.
