### ISSUE TITLE
Monadic parseOnly

### ISSUE THREAD

**Issue by zudov** [bos/attoparsec#95]
Often it's necessary to run a parser inside another parser. It's usually done with something like this:

```haskell
captureAndParse = do
    raw <- capture
    case parseOnly parse raw where
        Left err -> fail err
        Right res -> return res 
```

It would be nice to have a function `parseOnlyM` which runs a parser and calls `fail` on `Left` result. It can be implemented in this way:

```haskell
parseOnlyM :: Monad m => Parser a -> Text -> m a
parseOnlyM parser input = either fail return $ parseOnly parser input
```

Which would allow to simplify the first example to following:

```haskell
captureAndParse = capture >>= parseOnlyM parse
```

What do you think about such addition? I would be happy to make a PR.

**Comment by solatis** [comment]
Perhaps what we're really looking for here is a combinator that wraps this ? It looks like a pattern that should be captured (pun intended :)) on a higher level.

**Comment by bos** [comment]
`fail` is definitely not the right function to be using here, sorry.
