### ISSUE TITLE
safe `string` parsing alternative

### ISSUE THREAD

**Issue by solatis** [bos/attoparsec#97]
As you might know, there is some confusion around the behavior of the `string` parser, specifically in the following situation:

`parse (string "wombat" <|> string "foo") "foo"`

returns a Partial. This is due to the implementation of `string`:

```
string :: ByteString -> Parser ByteString
string s = takeWith (B.length s) (==s)
```

The solution proposed by various people on StackOverflow is to simply signal to Attoparsec when the end of the input has been reached, so it knows that the first branch of `string "wombat"` will never complete. This is undesirable in certain situations where you simply do not know if you reach the end of the input (specifically in network programming), and thus a safe alternative is desired.

I propose the following safe alternative of string, string':

```
string' :: ByteString -> Parser ByteString
string' = mapM (satisfy . (==)) . unpack
```

This will fail with the first character that makes the first branch impossible, and gives the desired result in many situations. The only situation that this will still return a partial is when you do (string "foo" <|> string "foobar"), but at least that one is more obvious.

Any comments?

**Comment by bos** [comment]
Oops, I didn't know about this, but it makes a lot of sense. I'm working on a fix.

Thanks for bringing this to my attention!

**Comment by bos** [comment]
I've fixed this for both `ByteString` and `Text`. Amusingly, the replacement functions are both more correct (due to exiting early) and *faster* by about 2x.

**Comment by solatis** [comment]
Great, thanks for the quick fix!
