### ISSUE TITLE
Speed up range checking

### ISSUE THREAD

**Issue by treeowl** [bos/attoparsec#98]
`isDigit`, `digit`, etc., are less smart than `isDigit_w8`. Specifically, they check ranges using code like
```haskell
'0' <= c && c <= '9'
```
This involves two comparisons and two branches. It's generally faster to use these:
```haskell
-- Requires, but does not check, that the third argument is at least
-- as large as the first.
betweenI :: Integral n => n -> n -> n -> Bool
betweenI a b c = (fromIntegral (b - a) :: Word) <= fromIntegral (c - a)
{-# INLINE betweenI #-}

betweenE :: Enum n => n -> n -> n -> Bool
betweenE a b c = betweenI (fromEnum a) (fromEnum b) (fromEnum c)
{-# INLINE betweenE #-}
```

The `c-a` will be calculated at compile time in typical uses, so this requires just one subtraction, one comparison, and one branch. The improvement is greatest when values are mostly *not* in the specified range (as branch prediction may be substantially improved), but even when branches are well-predicted, this way is a bit better.

**Comment by bos** [comment]
Someone submitted a pull request to this effect a while ago, and it had no measurable impact on performance. The right way to make progress on this is to submit a pull request with criterion benchmarks that demonstrate a difference.

**Comment by treeowl** [comment]
It's pretty easy to make artificial benchmarks to demonstrate a difference, by using a just-barely-pseudorandom-enough character list. I'll try to get around to it at some point, I suppose.
